# See the pacman.conf(5) manpage for option and repository directives
# general options
[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 8
DownloadUser = alpm
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
# main packages
[core]
Include = /etc/pacman.d/mirrorlist
# additional packages
[extra]
Include = /etc/pacman.d/mirrorlist
# 32-bit support
[multilib]
Include = /etc/pacman.d/mirrorlist

