-- Ensure the autogenerated warning is turned off explicitly
hl.config({ autogenerated = false })

-- 1. Monitor configuration
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1
})

-- 2. Performance & Display Settings
hl.config({
    misc = {
        disable_hyprland_logo = true
    },
    animations = {
        enabled = false
    }
})

-- 3. System Keybind (ALT + Q to close windows)
-- hl.bind("ALT", "Q", "killactive")

-- 4. Greeter Autostart Lifecycle
hl.on("hyprland.start", function ()
    hl.exec_cmd("nwg-hello; hyprctl dispatch exit")
end)
