# monitor
monitor=,preferred,auto,1
# application variables
$notificationDaemon = mako
$terminalEmulator = kitty
$fileManager = thunar
$menuLauncher = hyprlauncher
$statusBar = waybar
$wallpaperUtility = hyprpaper
$webBrowser = vivaldi
$webAltBrowser = chromium
# autostart applications
exec-once = $notificationDaemon
exec-once = $wallpaperUtility
exec-once = $statusBar
exec-once = $terminalEmulator
# enviroment
# -- cursor
env = XCURSOR_SIZE,16
env = HYPRCURSOR_SIZE,16
# keybindings
$superKey = SUPER
bind = $superKey, RETURN, exec, $terminalEmulator
bind = $superKey, R, exec, $menuLauncher
bind = $superKey, E, exec, $fileManager
bind = $superKey, B, exec, $webBrowser
bind = $superKey ALT, B, exec, $webAltBrowser
bind = $superKey, E, exec, $fileManager
bind = $superKey, F, fullscreen,
bind = $superKey, V, togglefloating,
bind = $superKey CONTROL, C, killactive,
bind = $superKey CONTROL, ESCAPE, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
# -- Move focus in current workspace
bind = $superKey, left, movefocus, l
bind = $superKey, right, movefocus, r
bind = $superKey, up, movefocus, u
bind = $superKey, down, movefocus, d
# -- Switch workspaces
bind = $superKey, 1, workspace, 1
bind = $superKey, 2, workspace, 2
bind = $superKey, 3, workspace, 3
bind = $superKey, 4, workspace, 4
bind = $superKey, 5, workspace, 5
bind = $superKey, 6, workspace, 6
bind = $superKey, 7, workspace, 7
bind = $superKey, 8, workspace, 8
bind = $superKey, 9, workspace, 9
bind = $superKey, 0, workspace, 10
# -- Move active window to a workspace
bind = $superKey SHIFT, 1, movetoworkspace, 1
bind = $superKey SHIFT, 2, movetoworkspace, 2
bind = $superKey SHIFT, 3, movetoworkspace, 3
bind = $superKey SHIFT, 4, movetoworkspace, 4
bind = $superKey SHIFT, 5, movetoworkspace, 5
bind = $superKey SHIFT, 6, movetoworkspace, 6
bind = $superKey SHIFT, 7, movetoworkspace, 7
bind = $superKey SHIFT, 8, movetoworkspace, 8
bind = $superKey SHIFT, 9, movetoworkspace, 9
bind = $superKey SHIFT, 0, movetoworkspace, 10
# -- Scroll through existing workspaces
bind = $superKey ALT, left, workspace, e-1
bind = $superKey ALT, right, workspace, e+1
# -- Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $superKey, mouse:272, movewindow
bindm = $superKey, mouse:273, resizewindow
# -- Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

