#!/usr/bin/env bash
# this is a simple config for herbstluftwm
hc() {
    herbstclient "$@"
}
hc emit_hook reload
# not forget to install `feh`
feh --bg-scale /usr/share/backgrounds/archlinux/wave.png
# keybindings
# -- remove all existing keybindings
hc keyunbind --all
# -- super key
Super=Mod4   # Use the super key as the main modifier
# -- core
hc keybind $Super-Control-Escape quit
hc keybind $Super-Shift-r reload
hc keybind $Super-Control-c close
hc keybind $Super-Return fullscreen toggle
hc keybind $Super-v set_attr clients.focus.floating toggle
# -- spawn
hc keybind $Super-t spawn "${TERMINAL:-xterm}" # super terminal, xterm fallback, TERMINAL exported in .xsession
hc keybind $Super-b spawn chromium # super browser
hc keybind $Super-c spawn code # super code editor
# -- layouting
hc keybind $Super-space cycle_layout +1 vertical horizontal grid vertical
# -- focus cycling
hc keybind $Super-Tab         cycle_all +1
hc keybind $Super-Shift-Tab   cycle_all -1
# -- focusing clients
hc keybind $Super-Left  focus left
hc keybind $Super-Down  focus down
hc keybind $Super-Up    focus up
hc keybind $Super-Right focus right
# -- shifting clients
hc keybind $Super-Shift-Left  shift left
hc keybind $Super-Shift-Down  shift down
hc keybind $Super-Shift-Up    shift up
hc keybind $Super-Shift-Right shift right
# -- tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Super-$key" use_index "$i"
        hc keybind "$Super-Shift-$key" move_index "$i"
    fi
done
# -- cycle
hc keybind $Super-Alt-Right use_index +1 --skip-visible
hc keybind $Super-Alt-Left  use_index -1 --skip-visible
# mousebindings
# -- remove all
hc mouseunbind --all
# -- basic left and right mouse buttons
hc mousebind $Super-Button1 move
hc mousebind $Super-Button3 resize
# theme
# -- set
hc set frame_bg_transparent on
hc set frame_border_width 0
hc set frame_padding 0
hc set tree_style '╾│ ├└╼─┐'
hc set window_gap 8
# -- attr
hc attr theme.active.color "#488"
hc attr theme.border_width 1
hc attr theme.normal.color "#111"
# rules
# -- remove all
hc unrule -F
# -- basic
hc rule fixedsize floating=on
hc rule floatplacement=smart
hc rule focus=on # normally focus new clients
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
# unlock, just to be sure
hc unlock

